sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t dupred/multi-client -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true dupred/multi-client npm test

after_success:
    - docker build -t dupred/multi-client ./client
    - docker build -t dupred/multi-nginx ./nginx
    - docker build -t dupred/multi-server ./server
    - docker build -t dupred/multi-worker ./worker
    # Login to Docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub dsfgsd
    - docker push dupred/multi-nginx
    - docker push dupred/multi-server
    - docker push dupred/multi-worker
    - docker push dupred/multi-client

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-1-570317715919
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
